# Generated by Django 3.0.10 on 2020-09-19 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('audio_original', models.FileField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='pi'), validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('audio_cleaned', models.FileField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='pi'), validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
