# Generated by Django 3.2.5 on 2022-01-07 18:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20220107_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('first_recording_date', models.DateField()),
            ],
            options={
                'ordering': ['-first_recording_date'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.playlist')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.talk')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='talks',
            field=models.ManyToManyField(through='talks.PlaylistTalk', to='talks.Talk'),
        ),
    ]
