# Generated by Django 4.0.1 on 2022-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_playlist_created_at_playlist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='first_recording_date',
            field=models.DateField(null=True),
        ),
    ]
