# Generated by Django 3.2.11 on 2022-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_talk_audio_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttalk',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='playlisttalk',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='talk',
            name='transcription',
            field=models.TextField(help_text='The transcription of the audio is formatted in a specific way:"[timestamp @speaker_name] all text of paragraph (new line)". For example: <br>[0:00:00.0 @student] Some question.<br>[0:00:10.4 @culadasa] Answer to question.', null=True),
        ),
    ]
