# Generated by Django 4.0.8 on 2023-01-02 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields
import talks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0009_talk_original_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='transcription_deepgram',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='talks',
            field=talks.models.SortableManyToManyField(through='talks.PlaylistTalk', to='talks.talk'),
        ),
        migrations.CreateModel(
            name='TalkMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'view'), (2, 'download')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talk_metric', to=settings.AUTH_USER_MODEL)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.talk')),
            ],
        ),
    ]
