# Generated by Django 4.0.8 on 2023-01-02 16:31

import django.core.validators
from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_remove_talk_audio_filename_alter_talk_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='recorded_date',
            field=models.DateField(blank=True, help_text='Date when talk was recorded, if known.', null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='audio_cleaned',
            field=models.FileField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='{instance.id}/cleaned.mp3'), validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
        migrations.AlterField(
            model_name='talk',
            name='audio_original',
            field=models.FileField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='{instance.id}/original.mp3'), validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
