# Generated by Django 4.0.8 on 2023-01-02 16:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_talk_recorded_date_alter_talk_audio_cleaned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='A short description about the talk. Not the transcription itself.', null=True),
        ),
    ]
