# Generated by Django 4.0.8 on 2023-01-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_alter_talk_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkmetric',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='talkmetric',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
