# Generated by Django 4.0.8 on 2023-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0016_talk_audio_length_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='audio_length_seconds',
        ),
        migrations.AddField(
            model_name='talk',
            name='audio_length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
